spring:
    application:
        name: EventWaiter
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/event
        username: event
        password: password

    liquibase:
        change-log: classpath:liquibase/master.xml
        enabled: true
